version: "3.0"

services:
  db:
    image: postgres:13.4
    restart: always
    environment:
      POSTGRES_PASSWORD: SuperSecret
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:5.6
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - 8080:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:
