#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <folder>" >&2
  exit 1
fi

cd $1
python3 ../check-files.py required-files.yml

#cd ..
#if [ $?  -eq 0 ]; then
#  while true; do
#      read -p "Do you wish to zip the folder? " yn
#      case $yn in
#          [Yy]* ) zip -r $1.zip $1; break;;
#          [Nn]* ) exit;;
#          * ) echo "Please answer yes or no.";;
#      esac
#  done
#fi

